### ISSUE TITLE
FileNotFoundError for non-existent symbolic link

### ISSUE THREAD

**Issue by interrato** [edoardobortolozzo/PathCrawler#8]
## Environment
* OS: NixOS 20.09.3368.16fc9eb7364
* PathCrawler version: 1.1

## What were you trying to do
Executing `python3 pathcrawler.py /home/simone/.config/marktext/`

## What happened
On Linux, when a non-existent symbolic link is found a `FileNotFoundError` is raised.
```shell
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/nix/store/26fs7idnfcd4bfr3vcggr6xjzhndlyfb-python3-3.8.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/nix/store/26fs7idnfcd4bfr3vcggr6xjzhndlyfb-python3-3.8.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/simone/pathcrawler/pathcrawler/utils.py", line 8, in getFileHash
    with open(str(element),"rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/simone/.config/marktext/SS'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pathcrawler.py", line 38, in <module>
    hashmap, duplicatesExist = addFileHashesIterative(Path(path), args.exclude)
  File "/home/simone/pathcrawler/pathcrawler/core.py", line 68, in addFileHashesIterative
    hashmap, duplicatesExist = lib.updateHashmap(hashmap, files)
  File "/home/simone/pathcrawler/pathcrawler/utils.py", line 22, in updateHashmap
    arr = list(zip(files, pool.map(getFileHash, files)))
  File "/nix/store/26fs7idnfcd4bfr3vcggr6xjzhndlyfb-python3-3.8.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/nix/store/26fs7idnfcd4bfr3vcggr6xjzhndlyfb-python3-3.8.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/simone/.config/marktext/SS'
```

**Comment by interrato** [comment]
The `win32com` library must be added to a `requirements.txt` file or something.
